### ISSUE TITLE
Fails to build a working jar at current version

### ISSUE THREAD

**Issue by HaraldKorneliussen** [osgi/osgi.enroute.examples.eval#3]
Hello,

Recently some things changed (in the bnd-export-maven-plugin I believe, but I am not sure) which first caused lots of warnings to appear, like this: 

```
[WARNING] Warning : Snapshot and/or buildnumber not set aQute.maven.provider.MetadataParser$Snapshot@40fb8c86 in org.osgi:osgi.enroute.examples.eval:1.0.0-SNAPSHOT
[WARNING] Warning : Snapshot and/or buildnumber not set aQute.maven.provider.MetadataParser$Snapshot@3ddd547 in org.osgi:osgi.enroute.examples.eval.parsii.provider:1.0.0-SNAPSHOT
[WARNING] Warning : Snapshot and/or buildnumber not set aQute.maven.provider.MetadataParser$Snapshot@14488bdf in org.osgi:osgi.enroute.examples.eval.test:1.0.0-SNAPSHOT
[WARNING] Warning : Snapshot and/or buildnumber not set aQute.maven.provider.MetadataParser$Snapshot@9455b55 in org.osgi:osgi.enroute.examples.eval.api:1.0.0-SNAPSHOT

```

As of today, it appears to build successfully, but when trying to run the jar you get this error message:

```
Exception in thread "main" java.lang.NoClassDefFoundError: aQute/lib/io/IO
	at aQute.launcher.pre.EmbeddedLauncher.toFileURL(EmbeddedLauncher.java:56)
	at aQute.launcher.pre.EmbeddedLauncher.main(EmbeddedLauncher.java:36)
Caused by: java.lang.ClassNotFoundException: aQute.lib.io.IO
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 2 more
```

I notice aQute.lib.io.IO in the bnd project was latest modified today.

This might more correctly be an issue on the bnd or enroute projects, but I'm not confident enough to say, all I know is this project doesn't build.

**Comment by bjhargrave** [comment]
This may be my fault due to bnd changes I made. Let me look into it.
