### ISSUE TITLE
Unable to run the osgi.enroute.examples.eval example

### ISSUE THREAD

**Issue by nport** [osgi/osgi.enroute.examples.eval#6]
Once compiled the user should be able to run the example. With the following command the framework actually starts but the gogo shell prompt do not appear (we are in the bndrun directory):

 $> java -jar osgi.enroute.examples.eval.jar

It is not clear why it happens ...

After importing the projects in eclipse and running the bndrun file it seems that probably the issue is related to this error:

`Exception in thread "OSGi enRoute Gogo Shell" java.lang.UnsatisfiedLinkError: Could not load library. Reasons: [no jansi in java.library.path]
	at org.fusesource.hawtjni.runtime.Library.doLoad(Library.java:182)
	at org.fusesource.hawtjni.runtime.Library.load(Library.java:140)
	at org.fusesource.jansi.internal.CLibrary.<clinit>(CLibrary.java:42)
	at org.fusesource.jansi.AnsiConsole.wrapOutputStream(AnsiConsole.java:48)
	at org.fusesource.jansi.AnsiConsole.<clinit>(AnsiConsole.java:38)
	at jline.AnsiWindowsTerminal.detectAnsiSupport(AnsiWindowsTerminal.java:57)
	at jline.AnsiWindowsTerminal.<init>(AnsiWindowsTerminal.java:27)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
	at java.lang.reflect.Constructor.newInstance(Unknown Source)
	at java.lang.Class.newInstance(Unknown Source)
	at jline.TerminalFactory.getFlavor(TerminalFactory.java:211)
	at jline.TerminalFactory.create(TerminalFactory.java:102)
	at jline.TerminalFactory.get(TerminalFactory.java:186)
	at jline.TerminalFactory.get(TerminalFactory.java:192)
	at osgi.enroute.gogo.shell.provider.Shell$1.run(Shell.java:153)
	at java.lang.Thread.run(Unknown Source)`

**Comment by nport** [comment]
Suddently came to mind that a guy sent an emial to the the osgi-dev mailing list in October 2016, describing a similar problem. He was having it on Windows 10 and I am using Windows 10 too.
I guess that this issue now requires more attention, since, Windows 10 is replacing all the previous Windows versions.

**Comment by pkriens** [comment]
You should make sure to use the Felix Gogo shell, the OSGi enRoute shell that Neil Bartlett provided did not work well on Windows.

Kind regards,

	Peter Kriens

**Comment by nport** [comment]
I discovered my issue is a duplicate of  issue 17 of the osgi.enroute project.

**Comment by wsargent** [comment]
That sounds like a Logback issue: https://logback.qos.ch/manual/layouts.html#coloring https://jira.qos.ch/browse/LOGBACK-762
